server:
  port: 80

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/demo
    url: jdbc:mysql://47.103.22.205:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mj.springcloud.entities

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
    serviceUrl:
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      defaultZone: http://localhost:7001/eureka